/* Generated by tools/serve.py from the contents of photos/.
   The deploy workflow regenerates this the same way. */
window.GALLERY_PHOTOS = [
  "photos/Screenshot 2026-08-29 at 10.20.45 PM.png",
  "photos/Screenshot 2026-08-29 at 10.20.59 PM.png",
  "photos/Screenshot 2026-08-29 at 10.21.11 PM.png",
  "photos/Screenshot 2026-08-29 at 10.21.53 PM.png",
  "photos/Screenshot 2026-08-29 at 10.22.23 PM.png",
  "photos/Screenshot 2026-08-29 at 10.22.34 PM.png",
  "photos/Screenshot 2026-08-29 at 10.22.43 PM.png",
  "photos/Screenshot 2026-08-29 at 10.22.52 PM.png",
];
