#!/usr/bin/env python3
"""Local preview server for the site.

Serves the repo on http://localhost:8735 and regenerates photos/photos.js from
the actual contents of photos/ on every request, mirroring what the deploy
workflow does on GitHub. Drop images in photos/ and reload the gallery.

    python3 tools/serve.py [port]
"""

import http.server
import os
import socketserver
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PHOTOS = os.path.join(ROOT, "photos")
EXTS = (".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif")


def build_manifest():
    try:
        names = sorted(
            f for f in os.listdir(PHOTOS)
            if f.lower().endswith(EXTS) and not f.startswith(".")
        )
    except OSError:
        return
    body = "".join('  "photos/%s",\n' % n for n in names)
    text = ("/* Generated by tools/serve.py from the contents of photos/.\n"
            "   The deploy workflow regenerates this the same way. */\n"
            "window.GALLERY_PHOTOS = [\n%s];\n" % body)
    path = os.path.join(PHOTOS, "photos.js")
    try:
        with open(path) as fh:
            if fh.read() == text:
                return
    except OSError:
        pass
    with open(path, "w") as fh:
        fh.write(text)
    print("photos.js: %d image%s" % (len(names), "" if len(names) == 1 else "s"))


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=ROOT, **kwargs)

    def do_GET(self):
        if self.path.split("?")[0].endswith("/photos/photos.js"):
            build_manifest()
        return super().do_GET()

    def end_headers(self):
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def log_message(self, fmt, *args):
        pass


if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 8735
    build_manifest()
    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(("", port), Handler) as httpd:
        print("Serving %s at http://localhost:%d  (ctrl-C to stop)" % (ROOT, port))
        httpd.serve_forever()
